### ISSUE TITLE
Suggestion:add bandcamp search

### ISSUE THREAD

**Issue by Tomato6966** [TopiSenpai/LavaSrc#11]
Bandcamp has simple api

I made an erela plugin so if u want references
https://github.com/Tomato6966/erela.js-bandcamp-search

Would be useful maybe

Also add deezer search filters..

**Comment by TopiSenpai** [comment]
??
https://github.com/Walkyst/lavaplayer-fork/tree/original/main/src/main/java/com/sedmelluq/discord/lavaplayer/source/bandcamp
