### ISSUE TITLE
Error while loading Yandex Music playlist

### ISSUE THREAD

**Issue by blad3fear** [TopiSenpai/LavaSrc#111]
When trying to search a playlist from Yandex Music lavalink shows me an error

![image](https://github.com/topi314/LavaSrc/assets/15636011/4749a778-1e97-426f-aea6-ef68ca485cf1)

**Comment by topi314** [comment]
fixed in https://github.com/topi314/LavaSrc/releases/tag/3.2.8 and https://github.com/topi314/LavaSrc/releases/tag/4.0.0-beta.5
