### ISSUE TITLE
Spotify Playlist Loading

### ISSUE THREAD

**Issue by fb-sean** [TopiSenpai/LavaSrc#17]
We have 2 playlists that drops 2 diffrent errors:

1. Playlist => https://open.spotify.com/playlist/0kAUzkna7u36QdsRofMq3I
1. Error => https://sourceb.in/HbZ4yO9A4U

2. Playlist => https://open.spotify.com/playlist/5OLKi4LzRbeYPoFOidZPK5
2. Error => https://sourceb.in/l5TNiF7Ynf

**Comment by Tomato6966** [comment]
Great!

**Comment by TopiSenpai** [comment]
should be fixed in https://github.com/TopiSenpai/LavaSrc/releases/tag/3.0.6
