### ISSUE TITLE
Deezer Thumbnails

### ISSUE THREAD

**Issue by Tomato6966** [TopiSenpai/LavaSrc#22]
Deezer is not providing artwork urls anymore
but keeps providing the md5_image tag:

you can get the thumbnail by: 
```js
`https://cdns-images.dzcdn.net/images/cover/${deezerSearchRes.md5_image}/500x500.jpg`
```

**Comment by TopiSenpai** [comment]
as far as I can tell `track.album.cover_xl` still exists
