### ISSUE TITLE
Deezer help

### ISSUE THREAD

**Issue by Rocky-pup** [TopiSenpai/LavaSrc#27]
I have an error when trying to play from deezer:
![изображение](https://user-images.githubusercontent.com/83218418/198896229-d7489a2c-5a03-48d6-8ecd-f1828a9a8b9c.png)

What i am dong wrong?

Lavalink v.3.6.1 (localhost)
LavaSrc: 3.1.3
Wraper: Tomato6966/erela.js (latest)

**Comment by TopiSenpai** [comment]
please link what track causes this
but this is prob just a temporary problem

**Comment by Rocky-pup** [comment]
any
https://deezer.page.link/dC5oQhQ2NTxf9Acr8

**Comment by Rocky-pup** [comment]
also search give me same thing
![изображение](https://user-images.githubusercontent.com/83218418/198896946-e06af5b7-3721-4986-a5ae-106d500d7530.png)

**Comment by TopiSenpai** [comment]
you do have the deezer master encrypton key configured correctly?
works fine for me

**Comment by Rocky-pup** [comment]
![изображение](https://user-images.githubusercontent.com/83218418/198897025-ba2c5456-0d4a-4bf0-a0ad-6904ce446ab9.png)

**Comment by TopiSenpai** [comment]
I assume you have it filled out differnently right

**Comment by Rocky-pup** [comment]
what do you mean?

**Comment by TopiSenpai** [comment]
you do not have it filled with `getitsomehow-use-google` right

**Comment by Rocky-pup** [comment]
ok, i'll try more

**Comment by Rocky-pup** [comment]
i can't understand how i need to get it, anyway thanks for help

**Comment by Rocky-pup** [comment]
now i have another problem - very bad quality of sound and this error in console

![изображение](https://user-images.githubusercontent.com/83218418/198957953-4211fed0-8dba-4b16-acc3-6ada919d04fd.png)

**Comment by Rocky-pup** [comment]
o, nvm i still have not right key

**Comment by TopiSenpai** [comment]
Do you have the correct master decryption key configured now?

**Comment by Rocky-pup** [comment]
Nope, I just can't find it. If I understand right I need track XOR key, right? I already have gateway key but it's not working

**Comment by zRickz** [comment]
Waiting for solutions too 😕

**Comment by TopiSenpai** [comment]
There is no additional clarification needed
Everyone else found the key without any issue
