### ISSUE TITLE
Issue with Deezer Track Play

### ISSUE THREAD

**Issue by fb-sean** [TopiSenpai/LavaSrc#30]
Hey I have this issue when I try to play something :/ 

![QE0DLt4I](https://user-images.githubusercontent.com/71556073/201493809-1c45f8e3-90c0-4a10-a3da-a598331c1346.png)

Is this from me? And when yes what do I need to do?

**Comment by TopiSenpai** [comment]
From what I can can tell looking at your logs your configuration is wrong

Don't include `""`

**Comment by fb-sean** [comment]
Ok thx
