### ISSUE TITLE
Thumbnails not returning

### ISSUE THREAD

**Issue by Tomato6966** [TopiSenpai/LavaSrc#35]
![image](https://user-images.githubusercontent.com/68145571/203378426-061f60ec-2129-4686-9e10-817f726e8441.png)

In order to receive thumbnails / cover images / artwork images
you need to use the md5_image tag provided from deezer.com's api

they recently remvoed the thumbnail image property from track objects

here is a way of ways to do it with strings by using the md5_image property which you'll often get!

If it's available return the thumbnail pls ;)

if(data.md5_image) track.thumbnail = `https://e-cdns-images.dzcdn.net/images/user/${data.md5_image}/500x500.jpg`

THANKS

**Comment by TopiSenpai** [comment]
idk for me they send cover in every track|
`GET` `https://api.deezer.com/2.0//search?q=Sexbomb`
https://hastebin.de/toluxeduco.json

**Comment by Tomato6966** [comment]
> idk for me they send cover in every track

i think you didn't check the output quite right-

You receive ALBUM covers (the md5_image code you also get)
and ARTISTS pictures (images)
but you do not add it to the track INFO OBJECT, neither the md5_image code nor, a URL for the thumbnail

**Comment by Tomato6966** [comment]
I think something is wrong with your artworkURL property

**Comment by Tomato6966** [comment]
oh wait, I think we missunderstand us
> are you not able to return the md5_image tag, or artworkURL to lavalink track info object(s) ?

**Comment by TopiSenpai** [comment]
That has never been a thing in lavalink.

**Comment by Tomato6966** [comment]
oh true yea, maybe a feature request to add additional meta data by plugins?

**Comment by TopiSenpai** [comment]
as there is nothing to do here I'm closing it
