### ISSUE TITLE
Yandex Music issue

### ISSUE THREAD

**Issue by Pelfox** [TopiSenpai/LavaSrc#57]
Yandex Music always returns "No Matches Found" when used with Lavalink.

[Logs](https://pastes.dev/SdMghqhug5)
[Configuration](https://pastes.dev/f9W8QzDsgd)
[Example song](https://music.yandex.ru/album/2849406/track/24442537)

**Comment by TopiSenpai** [comment]
@AgutinVBoy can you take a look?

**Comment by AgutinVBoy** [comment]
Try to play any podcast. For example, [this one](https://music.yandex.ru/album/6880204/track/111568695)

**Comment by AgutinVBoy** [comment]
> Yandex Music is very location-dependent. You should either have a premium subscription (Yandex Plus) or be located in one of the following countries: Azerbaijan, Armenia, Belarus, Georgia, Kazakhstan, Kyrgyzstan, Moldova, Russia, Tajikistan, Turkmenistan, Uzbekistan
Else you will only have access to podcasts.

**Comment by AgutinVBoy** [comment]
TBH, I don't know how to help. I was able to catch this issue only from a Non-premium account and from a German IP. 
Your token must be fine, otherwise you would be catching an authorization errors in the Lavalink logs.
