### ISSUE TITLE
Unknown Issue

### ISSUE THREAD

**Issue by AAYAN717628** [TopiSenpai/LavaSrc#58]
2|java    | 2023-04-06 11:32:40.958 ERROR 2600484 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 69QaMo9boUQPcNCN5ifu9W
2|java    | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
2|java    |     at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:293) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:38) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:58) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:50) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.github.topisenpai.lavasrc.mirror.MirroringAudioTrack.process(MirroringAudioTrack.java:50) ~[lavasrc-plugin-3.2.0.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:354) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
2|java    |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
2|java    |     at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
2|java    |     Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
2|java    |   lavaplayer.version: 1.3.99-original
2|java    |   os.arch: amd64
2|java    |   os.name: Linux
2|java    |   os.version: 5.4.0-42-generic
2|java    |   java.vendor: Ubuntu
2|java    |   java.version: 11.0.16
2|java    |   java.runtime.version: 11.0.16+8-post-Ubuntu-0ubuntu120.04
2|java    |   java.vm.version: 11.0.16+8-post-Ubuntu-0ubuntu120.04
2|java    | Caused by: java.lang.RuntimeException: Not success status code: 403
2|java    |     at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:87) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:123) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubePersistentHttpStream.internalRead(YoutubePersistentHttpStream.java:52) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:193) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at java.base/java.io.DataInputStream.readFully(DataInputStream.java:200) ~[na:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.container.matroska.format.MutableMatroskaBlock.getNextFrameBuffer(MutableMatroskaBlock.java:54) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:371) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:335) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:320) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:296) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275) ~[lavaplayer-1.3.99.jar!/:na]
2|java    |     ... 12 common frames om

**Comment by TopiSenpai** [comment]
That is a yt error
This has nothing to do with lavasrc
