### ISSUE TITLE
Yandex Search "Response code from channel info is 500"

### ISSUE THREAD

**Issue by ooliver1** [TopiSenpai/LavaSrc#63]
https://workbin.dev/?id=1682865077616363

I have specified a yandex token using `PLUGINS_LAVASRC_YANDEXMUSIC_ACCESSTOKEN: $YANDEX_TOKEN` and setting `YANDEX_TOKEN` to the token I got with these steps <https://github.com/TopiSenpai/LavaSrc#yandex-music>

It is 58 characters, and starts with `y0_AgAAAABo`, so hopefully thats a valid token.

**Comment by TopiSenpai** [comment]
@AgutinVBoy

**Comment by AgutinVBoy** [comment]
I checked the API path, it works. The token looks like it is correct. Check that you can connect to api.music.yandex.net. 
Do you have a premium subscription (Yandex plus)? Where is your server located?

**Comment by ooliver1** [comment]
Ah I really didn't read the README all too well, I am in the UK and the server is in the US.
