### ISSUE TITLE
Deezer Search categories [suggestions/question]

### ISSUE THREAD

**Issue by Tomato6966** [TopiSenpai/LavaSrc#67]
Hello!

How cool would it be, If users could make their searching-experience way more spezfic? Like searching for artists and their tracks, playlists, albums or even deezer-mixes (radios)?

Deezer's Api allow so many spezfications and filterings.
Down below a list of all possibilities.

In my opinion the most useful ones are: tracks, playlists, artists, albums.
But tbh I also like deezer-mixes (radios) which are pretty well mixed!

Currently we search by adding this prefix: `dzsearch:`

For those filtering we could do for example:
- `dzsearch-tracks:` / `dzsearch-playlists:`
- or `dzsearch:tracks:` / `dzsearch:playlists:`
- or something similar like that!

```js
// SEARCH everything
`https://api.deezer.com/search?q=${query.replaceAll(" ", "+")}&limit=100`;
// SEARCH albums only
`https://api.deezer.com/search/album?q=${query.replaceAll(" ", "+")}&limit=100`;
// SEARCH artists only
`https://api.deezer.com/search/artist?q=${query.replaceAll(" ", "+")}&limit=100`;
// SEARCH playlists only
`https://api.deezer.com/search/playlist?q=${query.replaceAll(" ", "+")}&limit=100`;
// SEARCH podcasts only
`https://api.deezer.com/search/podcast?q=${query.replaceAll(" ", "+")}&limit=100`;
// SEARCH radios/mixes only
`https://api.deezer.com/search/radio?q=${query.replaceAll(" ", "+")}&limit=100`;
// SEARCH tracks only
`https://api.deezer.com/search/track?q=${query.replaceAll(" ", "+")}&limit=100`;
// SEARCH users only
`https://api.deezer.com/search/user?q=${query.replaceAll(" ", "+")}&limit=100`;
// fetch all genre - playlsits
`https://api.deezer.com/genre`;
// get general playlist of charts (tracks + albums + playlists + podcasts)
`https://api.deezer.com/chart/0?limit=100`;
// get charts with only tracks
`https://api.deezer.com/chart/0/tracks?limit=100`;
// get charts with only albums
`https://api.deezer.com/chart/0/albums?limit=100`;
// get charts with only artists
`https://api.deezer.com/chart/0/artists?limit=100`;
// get charts with only playlists
`https://api.deezer.com/chart/0/playlists?limit=100`;
// get charts with only podcasts
`https://api.deezer.com/chart/0/podcasts?limit=100`;

// EVERYTHING DOWN BELOW requires the ID of something!


// fetch information about a track
`https://api.deezer.com/track/${ID}`;

// fetch information about an artist
`https://api.deezer.com/artist/${ID}`;
// fetch tracks of an artist
`https://api.deezer.com/artist/${ID}/top?limit=100`; // recommend to use paging!


// fetch an episode
`https://api.deezer.com/episode/${ID}`;

// fetch information about an album
`https://api.deezer.com/album/${ID}`;
// fetch tracks of an album
`https://api.deezer.com/album/${ID}/tracks?limit=100`; // recommend to use paging!

// fetch information about an artist
`https://api.deezer.com/artist/${ID}`;
// fetch tracks of an artist
`https://api.deezer.com/artist/${ID}/top?limit=100`; // recommend to use paging!

// fetch information about a podcast
`https://api.deezer.com/podcast/${ID}`;

// fetch information about a radio / mix playlist
`https://api.deezer.com/radio/${ID}`;
// fetch tracks of a radio / mix playlist
`https://api.deezer.com/radio/${ID}/tracks?limit=100`; // recommend to use paging!
```

**Comment by TopiSenpai** [comment]
While I'm not opposed to adding specific search categories, I do wonder how you expect me to return multiple playlists, albums, artists or users

Also please note `query.replaceAll(" ", "+")` is **NOT** sufficient URL encoding

**Comment by Tomato6966** [comment]
yes it's not a good url encoding, i just put it in there, so you know to search with + signs, you could also encode them

Hence deezer does not provide the tracks of a playlist, you'd need to fetch the tracks manually.

You could return a list (array) of playlist information, which then fetch the playlist via links

Since fetching the tracks of dutzend of playlists could result into ratelimits far more easily then doing a second lavalink request.
-> you should also fetch for playlist.public = true!

So it's like a rest endpoint
I do this manually client sided, and then just pass the playlsit link to lavalink for example
All a user needs is:
playlist.title = Name of the playlist
playlist.link = Uri of the playlist
playlist.user.name = Creator of the playlist
playlist.nb_tracks = tracks amount
playlist.creation_date = optional
playlist.md5_image for the cover/thumbnail or a direct cover/thumbnail link


Just an example.

**Comment by Tomato6966** [comment]
I think it would be neat, if you could "filter" the dzsearches, to allow "more spezific" searches via lavasrc
Only as a suggestion

**Comment by TopiSenpai** [comment]
Then please limit that feature request to that and do not include 1938 other things?

**Comment by Tomato6966** [comment]
I provided all possible possibilitites of more spezific search possibilities for deezer
Sorry for confusing you

**Comment by TopiSenpai** [comment]
Do you mind rephrasing your issue description?

**Comment by TopiSenpai** [comment]
You are still telling me to return playlists as search result

Yet lavaplayer nor lavalink does not support this

Nor did you remove any unnecessary endpoints

**Comment by TopiSenpai** [comment]
Just remove everything that is not relevant

Lavaplayer only supports returning tracks as search results, no playlists

**Comment by Tomato6966** [comment]
Well if that's the case, then that wouldn't work either way..

**Comment by TopiSenpai** [comment]
That's what I've been telling you the whole time...

**Comment by Tomato6966** [comment]
Sorry for taking your time..
