### ISSUE TITLE
New Spotify URL

### ISSUE THREAD

**Issue by fb-sean** [TopiSenpai/LavaSrc#72]
Spotify starts using "https://open.spotify.com/intl-de/track/0DfG1ltJnZyq4Tx3ZLL7ZU?si=adda475ffc4c4bbd" 

"intl-de" etc (now region specific links) as url and because of that lavasrc dont find any source. Idk what the best way would be to work against it I yet did it with a regex that filters the track id out. (In JS)

**Comment by TopiSenpai** [comment]
Will do on Saturday/Sunday as I'm currently on holiday.

Are there any docs on how this prefix comes together?
What does `intl` mean?

**Comment by fb-sean** [comment]
I think that have something with the language todo but I'm not sure I also didnt found any docs for that

**Comment by TopiSenpai** [comment]
Well, I assume it stands for international german

**Comment by fb-sean** [comment]
That would make sense I think the best would be to work with a regex that tries to filter /track/id from the link

**Comment by TopiSenpai** [comment]
The fixed regex would prob be
```regex
(https?://)?(www\\.)?open\\.spotify\\.com/(user/[a-zA-Z0-9-_]+/)?(?<region>[a-zA-Z-]+/)?(?<type>track|album|playlist|artist)/(?<identifier>[a-zA-Z0-9-_]+)
```

**Comment by TopiSenpai** [comment]
So you have any idea about the user playlists having the region aswell?

**Comment by fb-sean** [comment]
As far as I know they dont but the chances that they will get it too isnt low

**Comment by TopiSenpai** [comment]
well then this should be the saver option
```regex
(https?://)?(www\\.)?open\\.spotify\\.com/(?<region>[a-zA-Z-]+/)?(user/[a-zA-Z0-9-_]+/)?(?<type>track|album|playlist|artist)/(?<identifier>[a-zA-Z0-9-_]+)
```

**Comment by TopiSenpai** [comment]
released in https://github.com/TopiSenpai/LavaSrc/releases/tag/3.2.4
